# Generated by Django 4.0.1 on 2022-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_of',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
